### PR TITLE
delete captcha

### PR DESCRIPTION
**Pull request by szudena**

### CODE REVIEW

**Comment by hassuni** [comment]
Thanks @szudena

**Comment by szudena** [comment]
no problem please test
i am not at home to test it i have change to the hardcoded channel url

**Comment by hassuni** [comment]
I tested 2M and it work fine. no captcha

**Comment by szudena** [comment]
test please the premium channels like art aflam or bein sport note bein sport take time to open and the bein low are now the hd channels

**Comment by hassuni** [comment]
it work like a sharm, test art aflam and bein4. shokran
@Shani-08  can you please add szudena to team

**Comment by szudena** [comment]
no problem bro thx for test

**Comment by moe1999** [comment]
Yeah the only things is that it keeps on buffering!! It is probably from their servers. Don't you say

**Comment by allouch89** [comment]
bein sport buffers alot more than others, i dont know why. but if you are on wifi, you cant expect anything else

**Comment by szudena** [comment]
problem not from wifi or internet 
i have some premium idu and also can test it on website
problem from source

**Comment by moe1999** [comment]
How do you get premium idu

**Comment by norhan76** [comment]
The channels stopped working on my android box.

On Wed, Apr 15, 2015 at 7:54 PM, moe1999 <notifications@github.com> wrote:

> How do you get premium idu
>
> Sent from my iPhone
>
> > On Apr 15, 2015, at 5:14 PM, szudena <notifications@github.com> wrote:
> >
> > problem not from wifi or internet
> > i have some premium idu and also can test it on website
> > problem from source
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Shani-08/ShaniXBMCWork/pull/193#issuecomment-93600998>
> .
>



-- 
Norhan Hammad
Web/Graphic Designer
Phone: (302)743-7697

**Comment by moe1999** [comment]
What he premium idu anyways

**Comment by szudena** [comment]
@norhan76 no problem with channels working

**Comment by allouch89** [comment]
There is still some problems

**Comment by szudena** [comment]
@allouch89 with?

**Comment by allouch89** [comment]
with the network from teledunet

**Comment by szudena** [comment]
that is normal :)
https://www.facebook.com/TeleDuNet/posts/695241897236753

**Comment by Shani-08** [comment]
@szudena  is now a collaborator so it should be easier for him to make changes.,

**Comment by szudena** [comment]
@Shani-08 thx brother

**Comment by szudena** [comment]
@hassuni on kodi forum you have post a worng link for the Offcial.xml
royaliptv url

**Comment by hassuni** [comment]
@szudena thanks , you save me a day :-)

**Comment by szudena** [comment]
:)

**Comment by hassuni** [comment]
@szudena  did you get my email, I did asked you about this treath
http://www.sat-universe.com/showthread.php?t=262444&page=24

**Comment by szudena** [comment]
yes i have farfesh panet and more  is ready on kodi by hadynz and other

**Comment by szudena** [comment]
royaliptv will be added in the next arabicentertainemt
royal have more then 1000 streams if you dont know that

**Comment by hassuni** [comment]
I did not know it. I can not find 2M, do you have it
I can not see farfesh on arabic repo, where is the arabic repo,can you send the link
thanks

**Comment by szudena** [comment]
oh sry i have think farfesh is on arabic repo
https://github.com/hadynz/repository.arabic.xbmc-addons

**Comment by szudena** [comment]
for 2m change id to 172

**Comment by szudena** [comment]
but are shared url the url that you have is just a shortcut few channel are from other server

**Comment by allouch89** [comment]
what plugin are you guys talking about?

**Comment by szudena** [comment]
arabicentertainment for enigma2

**Comment by hassuni** [comment]
thanks for 2M.
can you please add farfesh and what is good on enigna to shahid or arabic repo.
I fid found this one http://159.8.125.15/somthing/ch1262/ and http://159.8.125.10/someting/ch1262/index.m3u8
but stoped working today

**Comment by hassuni** [comment]
if you like, I can send you the copmlet roylip list and you can add it to shahid

**Comment by szudena** [comment]
15 is down 10 maybe to new one you can finde it if you download 2m m3u8

**Comment by szudena** [comment]
i have all hassuni but not all named if you have all named way not you have my mail thx

**Comment by szudena** [comment]
but some channel you will have segment problem  will stop like osn and other

**Comment by hassuni** [comment]
10 ,stoped today too. will see. but maybe shani can do something before Published, maybe he can coded for people to copy paste.
I will send you the file with name give a a couple min

**Comment by szudena** [comment]
better dont public that shit for now maybe we can found a way to make it safe 
otherwise quickly down
the new one is 46.101.174.134

**Comment by hassuni** [comment]
we need to talk with shani to do the same like for teleunet.xml

**Comment by szudena** [comment]
yes better

**Comment by hassuni** [comment]
check you email

**Comment by szudena** [comment]
me and testi will add them on other plugins for enigma2 testi is my teacher :-)

**Comment by hassuni** [comment]
I did meet him, he gave me the royal.
do u have this one, I did added alot of channels

**Comment by hassuni** [comment]
http://arabic.dynns.com

**Comment by szudena** [comment]
yes i have named it and give it to testi but not all i have few new ids

**Comment by hassuni** [comment]
i will send it to you

**Comment by szudena** [comment]
i mean the royal not the arabic dynns

**Comment by szudena** [comment]
the arabic dynns i have only the old one but this need Auth..

**Comment by hassuni** [comment]
try rtmp format
rtmp://167.114.119.228/arabic/channel

**Comment by szudena** [comment]
aha that is it thx

**Comment by hassuni** [comment]
royalip file that send it to you, please change LCP to 2m (172)

**Comment by szudena** [comment]
for now i dont need it but thx we wait for shani better to make it like teledunet

**Comment by allouch89** [comment]
where can i find a full channel list for arabic.dynns.com ?

**Comment by szudena** [comment]
i have only some channel maybe hassuni have all

**Comment by hassuni** [comment]
@allouch89 put your email here and I will send you both file 
I just found a couple, you can find more

**Comment by allouch89** [comment]
allouch@live.dk
thanks brother, i will try to find some my self

**Comment by hassuni** [comment]
if you find some, just send me a email.
you can published for shani under generic.xml

**Comment by allouch89** [comment]
I will do, will check it after work

**Comment by hassuni** [comment]
@allouch89 can you add @szudena  as collaborator

**Comment by moe1999** [comment]
Why isn't the vods not working for me on shahid Arabic. It never did and I followed shanis instructions and still it would never work.

**Comment by hassuni** [comment]
maybe you are geoblock. try if it okay from mbc web site

**Comment by moe1999** [comment]
Yeah I am geoblocked

**Comment by hassuni** [comment]
@moe1999  you need to follow shani instructio
http://ge.tt/6ntkEHA2/v/0

**Comment by moe1999** [comment]
Can u walk me through them. Because when I downloaded the zip and installed from zip on kodi it doesn't download for me

**Comment by hassuni** [comment]
dont install the zip, open zip file and look on pfd file how you setup a proxy 
and Please make sure the url that you enter in the settings, must be with http://

**Comment by moe1999** [comment]
I don't get it😂😂

**Comment by moe1999** [comment]
Do I press on proxy the PHD file

**Pull request merged**
