### PR TITLE
dowload feature using youtube-dl and parsing regex from m3u and helix support

### PR DESCRIPTION
**Pull request by alibbaba**

### CODE REVIEW

**Comment by Shani-08** [comment]
I think we need to mention all the repos that are required to get the dependencies, for example youtube.dl and common resolver etc.

**Comment by Shani-08** [comment]
Also making you the contributor so that you could check in now.

**Comment by moe1999** [comment]
hey @Shani-08 whats wrong with GLarab HD servers.  they keep on buffering!

**Comment by moe1999** [comment]
ANY new @Shani-08

**Comment by moe1999** [comment]
@Shani-08 when will Shahid Arabic be fixed Bro!

**Comment by emadmahdi** [comment]
it looks like glarab had stopped the two servers of the med & hd for the non-proxy method ... while the proxy method is still available.

**Comment by moe1999** [comment]
what is the proxy method @emadmahdi

**Comment by Shani-08** [comment]
Guys please see where you guys are commenting. Please keep the repo clean. @moe1999 there is no ETA and you should know that. Do you think if we could fix it we would take time? this issue is closes so stop replying to this.

**Pull request merged**
