### PR TITLE
the links

### PR DESCRIPTION
**Pull request by mhd316**

### CODE REVIEW

**Comment by Shani-08** [comment]
Please follow the instructions, start with livetv.tn and update the file that i mentioned.
You are just creating new files which means nothing!
Please read the post on the site and understand it first.

**Comment by mhd316** [comment]
where is the instrucions  plz help me

**Comment by Shani-08** [comment]
see the files here, see how its already done for several examples.
https://github.com/Shani-08/ShaniXBMCWork/tree/master/plugin.video.shahidmbcnet/resources/community
for example, open the LivetvUrl file and see how its pointing to the urls. use the same method for missing channels. Make sure the channel exists in Channel.xml file, if not, add the channel. then send the update of both the files.

**Comment by mhd316** [comment]
hi shani 
i made an update in sport section can i show it

**Pull request closed without merging**
