### PR TITLE
Update glarabUrls.xml

### PR DESCRIPTION
**Pull request by nermada**

### CODE REVIEW

**Comment by Shani-08** [comment]
I have taking this change but please do test everything, for example, i guess Rotana Classic Low already exists. Thanks for your efforts

**Comment by allouch89** [comment]
Whats new here?

**Comment by moe1999** [comment]
hey guys, any news about the GLarab servers.  Mine still dont work properly.

**Comment by Shani-08** [comment]
@moe1999 GLArab server are rejecting and they have closed the loophole. 
Once we get a break we will update the server, though someone with GLbox or paid account will be a help. 
You are posting in code repeated areas. If a issue not open, you can open a new one. 
Now if you don't stop posting in totally irrelevant sections then it will never be fixed. Choice is yours.

**Comment by moe1999** [comment]
I due apologize. I'm just new to this. :)

**Comment by emadmahdi** [comment]
16 hours ago i scanned the while glarab network using the non-proxy method and nothing is available now except the low quality.

**Comment by Shani-08** [comment]
Yes, I think they are updating their servers. I still believe that m3u8 method is still active but little secured as not all platforms support proxy and the ports are opened but it returns 0 bytes. Having a GLBox or paid online account would clear this out.

**Comment by bryan3r3** [comment]
Shani,
Maybe I can help, how can I sign up for a paid online account without purchasing a GLBox? I couldn't find on GLArab's website where I can just purchase a web subscription.

**Comment by allouch89** [comment]
I dont think you can

**Comment by moe1999** [comment]
Are there any other way to bring back the servers.

**Comment by allouch89** [comment]
The IP's on glturk was acting the same way as glarab IP's, but they are now working again.
I just tried all HD/Med IP's for glarab, they are still not working.

**Comment by emadmahdi** [comment]
i just scanned the network ... there was some servers available but they disappeared again.

**Comment by allouch89** [comment]
Do you mind sending me the IP's ? I'll investigate further. You can send them to allouch@live.dk if you dont mind.

**Comment by emadmahdi** [comment]
The same old HD servers ... these two were working 30 minutes ago and now they stopped again.
38.99.146.42
38.99.146.44

**Comment by allouch89** [comment]
Hm. These two IP's are working with glturk LOW streams.

**Comment by allouch89** [comment]
oh no sry, glarab low streams

**Comment by emadmahdi** [comment]
anyways ... I just checked the whole network and nothing is available now except the old low quality.

**Comment by moe1999** [comment]
It's amazing how it only worked for like half an hour!

**Comment by moe1999** [comment]
Any news about GLarab

**Comment by moe1999** [comment]
Sent from

**Comment by Shani-08** [comment]
@moe1999 create a new issue and discuss what's your problem. 
Currently glarab is available in low quality only. 
For HD and Med etc you have to install Proxy. 
If you have any other issue don't open old issues create a new one and explain what's going on.

**Pull request merged**
