### PR TITLE
Create glarabProxyUrls.xml

### PR DESCRIPTION
**Pull request by allouch89**
I have checked every HD m3u8 link with the proxy method and tested with _HD, _Med, _Low and _LR and this is the result. I have created this file so you can see what is working and what isnt, you dont neccesary have to use it for the proxy method.
You can ignore the 'type' tag, this is only useful with the old m3u8 links.
And btw, the 'cname' tag values isnt the same as the glarabUrls.xml 'cname' tag values, if you decide that you want to use this file, i can create a new one with the correct 'cname' tag values.

Tested with:
8.21.48.20 for HD, Med and Low
8.21.48.116 for LR

### CODE REVIEW

**Comment by allouch89** [comment]
And im happy to announce that i finally know how to add multiple commits for a pull request :)

**Comment by Shani-08** [comment]
Ok good work. But need couple of things. 
1. Don't use 127.0.0.1, use $pip$ just in case we are able to run the proxy on the network pc. 
2. Make sure you use same cname as channels.xml otherwise it won't work. 
3. Do we need Low,LR and medium ip or shouldn't it use the ip returned by session call. The reason I am asking because we are not trying multiple ip in proxy mode. Right now for low and medium we pick session ip and for HD we pick first ip which means you could enter the ip directly if session is not giving us the right ip. This will allow us to remove ip settings from user.

**Comment by allouch89** [comment]
1. is easy to change.
2. i can do that if you want to use this file.
3. Low and LR dont use the same ip, the session is doesnt necessary work, because it always gives back the same IP as far as i have noticed. So you should make it work like the the old method, try all|etc.

**Comment by allouch89** [comment]
Another thing, does glarab have all the channels in HD or is some channels only med or low?

**Comment by allouch89** [comment]
If you are going to use this file for the proxy method, ill started creating a proper xml file with the correct cname value and without the type tags

**Comment by Shani-08** [comment]
You realise that right now there is no try all for proxy and it's using ip passed by session call? While HD uses first ip in the list. 
The reason is that this try that it would work or not, will be done by proxy and if it worked we probably not going to get the control back. 
If we really need to do try all then I have to think and see if it's possible. You can try and test the existing proxy channels and the low LR and medium should work and the ip won't be from list. Only hd comes from list which affectively means static.

**Comment by emadmahdi** [comment]
@allouch89 I think it is better that you slow down in changing the gl file ... I know I had put all possibilities but this is temporary because we need to know first who a full solution will be then you can proceed in testing and filtering the gl file.

As for the full IP list ... here is a link to it ... and btw it's already included in the settings except ip's for LR:

https://github.com/Shani-08/ShaniXBMCWork/commit/7e07e56b7856df7a385aeee473ee252982363b38

**Comment by allouch89** [comment]
I did this for my own sake to begin with, and now i can do it again pretty fast in case you need it with the proper names.
Like i wrote in the comment, I only created this file so you that can see what channels there is available in the proxy method and what channels isnt.

**Comment by Shani-08** [comment]
Thanks. I think we put this off at the moment as with the latest changes things are working better. 
Since you can block proxy and use free channels or use proxy and use both, the issue is not that urgent.

**Comment by allouch89** [comment]
Im closing this pull request.
If you need me to create a new file for proxy urls, with only the channels that are working let me know.
Also if you want me to add in the current glarabUrls.xml file, i can make a list with only the working channels for LR,Low,Med,HD,High.

**Pull request closed without merging**
