### PR TITLE
Update genericUrls.xml

### PR DESCRIPTION
**Pull request by nermada**
Youtube official channels

### CODE REVIEW

**Comment by Shani-08** [comment]
Thanks. Keep doing the good work. I'llmake you contributor after few more changes so that you can merge it yourself.

**Comment by nermada** [comment]
Thank you!

Nermeen

**Comment by nermada** [comment]
Hi Shani, 
Sorry, for too many questions, I'm still learning. Why can't I see the 'youtubelive' in sources? Does it need to go under your sources? If so, how do I do that?
Thanks.

**Comment by hassuni** [comment]
@nermada   channels name should be the same in Channels.xml example CBC2 should CBC 2 (space betwwen cbc anc 2 ) Alqahera W Alnas should be    AlQahera W Elnas........., alwas try first  to do a test on your pc

**Comment by nermada** [comment]
Thank you!

**Pull request merged**
