### PR TITLE
Added Bein HD

### PR DESCRIPTION
**Pull request by hawwach**

### CODE REVIEW

**Comment by allouch89** [comment]
Good work. But i think we already have too many channels starting with Al, you should have just called them Bein Sport ..

**Comment by hawwach** [comment]
Opps, didn't notice that,

**Comment by hawwach** [comment]
sorry, I am new to all this, how can I edit it to remove the AL ?

**Comment by allouch89** [comment]
I dont know, im also pretty new to this :)

**Comment by hawwach** [comment]
:) done

**Comment by hawwach** [comment]
Now I should wait @Shani-08 to verify if it's okay and merge it, right ?

**Comment by hassuni** [comment]
you need to change it like that
<streaminginfo>
<cname>Bein Sport 11</cname>
<title>HD</title>
<chnumber>ch866</chnumber>
<link>http://www.livetv.tn/Bein-Sport-HD-11-en-direct-live.html</link>
</streaminginfo>

**Comment by hassuni** [comment]
you need to add <  title  >HD  < / title >  after </ cname >
and change Bein Sport  HD 1 to Bein Sport 1 . channel name muss be  on channle list
or you can add them 
https://github.com/Shani-08/ShaniXBMCWork/blob/master/plugin.video.shahidmbcnet/resources/community/Channels.xml

**Comment by hassuni** [comment]
example
< streaminginfo >
        < cname>Eurosport 2 France<  /cname>
<   title>Low<   /title >
        < chnumber>ch905< /chnumber>
	<  link >http://www.livetv.tn/EuroSport-HD-2-en-direct-live.html<  /link>
</  streaminginfo>

**Comment by Shani-08** [comment]
please use the same channel name as its in channels.xml, dont create more channels with variation if exists arleady

**Comment by Shani-08** [comment]
Thanks added

**Comment by hawwach** [comment]
Thanks shani, works like a sharm.
I'll do the full list later

**Pull request merged**
