### PR TITLE
Update settings.xml

### PR DESCRIPTION
**Pull request by jmikha4**
Added the new HD server for GLARAB

### CODE REVIEW

**Comment by allouch89** [comment]
@jmikha4 .. it does not work.
Try for example this link:
http://38.99.146.40:7777/AlJadeed_HD.m3u8

**Comment by jmikha4** [comment]
Yes, we have to change the whole thing. but I have the link that works

**Comment by allouch89** [comment]
What do you mean by change the whole think?

**Comment by allouch89** [comment]
thing*

**Comment by jmikha4** [comment]
I mean GLARAB changed how then combine the link for each channel

**Comment by jmikha4** [comment]
*they

**Comment by allouch89** [comment]
Do you mind explain how then, maybe i can help.

**Comment by jmikha4** [comment]
I don't know if it is ok to put the link here

**Comment by allouch89** [comment]
Its up to you, you can also send it to my email allouch@live.dk

**Comment by Shani-08** [comment]
Please send emails. The server might be ok but we need the params. If you have details share in email

**Comment by jmikha4** [comment]
sure I'll email you in a minute

**Comment by jmikha4** [comment]
did you get my email guys?

**Comment by allouch89** [comment]
I did, but those links are used with http_proxy.exe, this we already know of.

**Comment by jmikha4** [comment]
I got you. sorry guys

**Comment by allouch89** [comment]
Dont be, you tried to help, thank you for that. Better luck next time :)

**Comment by Shani-08** [comment]
Yes thanks for trying.

**Comment by jmikha4** [comment]
No problem. thank you guys

**Comment by emadmahdi** [comment]
@Shani-08 ... i hope you received my email.

Anyways ... i think there is a glarab proxy somewhere available for the public ... which can be a good alternative to the personal glarab proxy ... such solution is needed for clients other than windows clients such as android & ios.

**Pull request closed without merging**
