### PR TITLE
Update genericUrls.xml

### PR DESCRIPTION
**Pull request by jmikha4**
Added 3 links and removed some not responding links

### CODE REVIEW

**Comment by Shani-08** [comment]
Thanks. I am making you the cotribute which means you can make changes without waiting. Please check and test before pushing changes as if the xml is not valid, I'll make all channels disappear.

**Comment by hassuni** [comment]
please add timeout=20 when you have rtmp links

**Comment by jmikha4** [comment]
Thank you @Shani-08 . I already do test it before making any change.
@hassuni  I added the timeout. Thanks for pointing that out.

**Comment by Shani-08** [comment]
Thanks, you are now contributor so any change you make will be available to everyone and you wont need to wait

**Pull request merged**
