### PR TITLE
Update glarabUrls.xml

### PR DESCRIPTION
**Pull request by MO99**
Converted HD feeds to Low

### CODE REVIEW

**Comment by emadmahdi** [comment]
This change is not needed at all ... the low quality channels that suppose to work are already there.

**Comment by MO99** [comment]
my understanding is that this would allow us to watch channels like MBC in Low Quality. Right now, only HD is available for it and that server is down.

**Comment by allouch89** [comment]
MBC is only available in HD, if the server is down, mbc is down aswell

**Comment by emadmahdi** [comment]
glarab like any other iptv companies ... they offer two types of channels:
1- Limited which includes some generic & news channels
2- Premium which includes all the Limited plus more channels such as drama

Currently the premium channels are not available except by using the proxy method that offers also the MED & HD channels for both premium & limited.

**Comment by MO99** [comment]
can you please tell me how to use the proxy method? I am not using a PC, I am using Android TV BOX with XBMC 13.2

**Comment by emadmahdi** [comment]
Proxy method needs a PC.

**Comment by allouch89** [comment]
Maybe someone can create a identical proxy for android or something else

**Pull request closed without merging**
