### PR TITLE
Update teledunetPlayer.py

### PR DESCRIPTION
**Pull request by szudena**

### CODE REVIEW

**Comment by moe1999** [comment]
nothing works with teledunet as of right now.  @szudena

**Comment by szudena** [comment]
no problem with the file tested now

**Comment by moe1999** [comment]
What should I do with your patch. Should it be installed on my kodi because it's not working for me

**Comment by szudena** [comment]
download the file and send it to C:\Users\youruser\AppData\Roaming\XBMC\addons\plugin.video.shahidmbcnet\resources\community if you are on pc

**Comment by moe1999** [comment]
I have an Amazon fire tv

**Comment by szudena** [comment]
download the zip and install it 
note the automatically update replaces the installed file

**Comment by moe1999** [comment]
Oh ok. So you want me to download the shahid Arabic zip file and then install it on my kodi

**Comment by szudena** [comment]
@Shani-08 and @hassuni we dont need the captcha for teledunet

**Comment by szudena** [comment]
@moe1999 if you cant wait yes do that:)

**Comment by moe1999** [comment]
Can I get your email

**Comment by moe1999** [comment]
:)

**Comment by szudena** [comment]
szudena@hotmail.de

**Comment by allouch89** [comment]
I have made an android app you can use with teledunet, in association with teledunet crew. right now its free if you want to use it while in beta. Get it from here: www.onlinebotservices.com/android/Teledunet.apk

**Comment by szudena** [comment]
@allouch89 thx for your work will try later

**Comment by allouch89** [comment]
Its only for android boxes btw. Forgot to mention that.

**Comment by szudena** [comment]
@allouch89 thx for Merging my pull request

**Comment by moe1999** [comment]
Hey man I sent you an email!! :)

**Comment by moe1999** [comment]
When I downloaded the app it told me to put in a username and password

**Comment by allouch89** [comment]
Yes, well it logins to the teledunet server to get the idu for your account

**Comment by allouch89** [comment]
This app is only for those who have a subscription with teledunet

**Comment by szudena** [comment]
@moe1999  put your login from teledunet and it is only for premium user

**Comment by szudena** [comment]
@allouch89 maybe you can write one for the user without premium 
to get the id0

**Comment by allouch89** [comment]
This app only work with a subscription for now. There will be some free channels in the future

**Comment by moe1999** [comment]
So I wont be able to go on to the app without a username

**Comment by szudena** [comment]
@allouch89 thx but you know premium work without subscription

**Comment by allouch89** [comment]
You wont be able to watch any channels without a working subcription

**Comment by allouch89** [comment]
They do? I didnt know

**Comment by moe1999** [comment]
So I don't need a subscription!!! I'm confused 😂😂😂😂😂

**Comment by szudena** [comment]
yes they do i have it on enigma2 receiver , and xbmc

**Comment by moe1999** [comment]
Howwww

**Comment by szudena** [comment]
you just need to write an android script to get the id0 after login 
and the random token part and user part

**Comment by moe1999** [comment]
Can u do one

**Comment by szudena** [comment]
I know nothing about android language otherwise I would write you a script
maybe you can add i python script or php script

**Comment by szudena** [comment]
@moe1999 do you have an enigma2 receiver?

**Comment by allouch89** [comment]
You say they work on xbmc too without subscription, but i just tried i can only play free channels

**Comment by szudena** [comment]
for me work here after update the teledunetplayer.py
bein sport and other premium

**Comment by allouch89** [comment]
I see, it works for me too now.
I had to update the teledunetplayer.py manually for it to work

**Comment by szudena** [comment]
:)

**Comment by moe1999** [comment]
How do you update manually

**Comment by szudena** [comment]
and note we dont need the captcha part i can take it out if you want

**Comment by szudena** [comment]
@moe1999 open addon and click download files

**Comment by moe1999** [comment]
I still don't know how to update the player haha. Can someone teach me

**Comment by moe1999** [comment]
I tried that. Wouldn't work

**Comment by moe1999** [comment]
Do I need a username and password in the setting

**Comment by szudena** [comment]
in windows works try it again

**Comment by szudena** [comment]
yes you need free login

**Comment by allouch89** [comment]
It didnt work for me either to click on download files, i had to update the file manually

**Comment by moe1999** [comment]
How did update it @alouch89

**Comment by allouch89** [comment]
C:\Users\Allouch\AppData\Roaming\Kodi\addons\plugin.video.shahidmbcnet\resources\community

Change Allouch to you computers username

**Comment by szudena** [comment]
@allouch89 if you need i can send you a py without captcha
he have an android box:)

**Comment by moe1999** [comment]
@allouch89 what do you mean by changing my computers username

**Comment by allouch89** [comment]
@szudena im still not sure how to get the links, im still new with xbmc coding language.

@moe1999 type open a folder and type in %appdata" in the path, then locate to:
Kodi -> addons -> plugin.video.shahidmbcnet -> resources -> community
Then open the file teledunetPlayer.py and replace everything with this file:
https://raw.githubusercontent.com/Shani-08/ShaniXBMCWork/master/plugin.video.shahidmbcnet/resources/community/teledunetPlayer.py

**Comment by allouch89** [comment]
Oh,are you using a android box?

**Comment by moe1999** [comment]
Yes an Amazon fire tv

**Comment by moe1999** [comment]
But I have Firefox on it

**Comment by moe1999** [comment]
@allouch89

**Comment by allouch89** [comment]
Im not sure how to do it with the amazon fire tv.
I suggest that you reinstall shahid, but im not sure if it will delete the files
If it doesnt, then you could reinstall xbmc. But im guessing thats alot of work. You can take a backup of your xbmc before doing so.

**Comment by moe1999** [comment]
Let me try re installing shahid first

**Comment by allouch89** [comment]
Good idea :)

**Comment by szudena** [comment]
so i have try it now teledunet work without captcha :)

**Comment by allouch89** [comment]
Anyway, good job @szudena :)

**Comment by allouch89** [comment]
Im heading to bed, good night

**Comment by moe1999** [comment]
Good night

**Comment by szudena** [comment]
@allouch89 thx good night

**Comment by moe1999** [comment]
@szudena. It still doesn't work

**Comment by moe1999** [comment]
How do you erase the captcha

**Comment by szudena** [comment]
wait i send you the addon you can delte the old one from box and install the new one maybe work for you this way

**Comment by moe1999** [comment]
It work for me now

**Comment by moe1999** [comment]
But it keeps on bufgerkng

**Comment by moe1999** [comment]
Buffering

**Comment by moe1999** [comment]
Do you have a phone. It can be easier to text!!

**Comment by szudena** [comment]
skype if you want

**Comment by moe1999** [comment]
Damn I don't have skypr

**Comment by moe1999** [comment]
It keeps on buffering. Try the channels on yours and see if it keeps on buffering

**Comment by szudena** [comment]
which channel

**Comment by moe1999** [comment]
Try Abu dhabi

**Comment by szudena** [comment]
works without buffering

**Comment by moe1999** [comment]
Really I don't think I updated the player then. Because every 30 seconds it has to keep buffering

**Comment by szudena** [comment]
here on PC no buffering
so now i go sleep have a good night maybe shani will change the fix later and make it better
but the buffering comes not from fix
i dont have an android box to test that

**Comment by moe1999** [comment]
Ok thx

**Comment by Shani-08** [comment]
thanks you could make change to skip the captcha or send me details.

**Comment by szudena** [comment]
ok no problem i will make change

**Comment by norhan76** [comment]
Thanks guys for your great effort. But, i don't know why it still buffering every 30 seconds on android box.

**Comment by allouch89** [comment]
Teledunet is having some internet problems since friday, i think thats why.
Also are you using wireless or cable?

**Comment by norhan76** [comment]
I'm using Wireless and I will try the cable now.

**Comment by szudena** [comment]
so i have delete the captcha part and add a new ip for the premium channels the ip works to for free channels

**Pull request merged**
